from fastapi import APIRouter
from .endpoints import auth, users, persons, cameras, falls, alerts, dashboard, health, metrics, system, ai_training, telegram_api, ws
api_router = APIRouter()
api_router.include_router(health.router, prefix="/health", tags=["health"])
api_router.include_router(auth.router, prefix="/auth", tags=["authentication"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(persons.router, prefix="/persons", tags=["persons"])
api_router.include_router(cameras.router, prefix="/cameras", tags=["cameras"])
api_router.include_router(falls.router, prefix="/falls", tags=["falls"])
api_router.include_router(alerts.router, prefix="/alerts", tags=["alerts"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(system.router, prefix="/system", tags=["system"])
api_router.include_router(ai_training.router, prefix="/ai", tags=["ai"])
api_router.include_router(telegram_api.router, prefix="/telegram", tags=["telegram"])
api_router.include_router(metrics.router, tags=["observability"])
api_router.include_router(ws.router, tags=["websocket"])
