import QtQuick 2.15

QtObject {
    // ============================================================
    // SentinelAI — Icon registry (SVG filenames in assets/icons)
    // Values are kebab-case names matching *.svg files.
    // ============================================================

    // ---- Navigation (9 sidebar items) ----
    readonly property string dashboard:        "layout-dashboard"
    readonly property string cameras:          "camera"
    readonly property string alerts:           "bell"
    readonly property string events:           "calendar"
    readonly property string users:            "users"
    readonly property string aiTraining:       "bot"
    readonly property string observability:    "activity"
    readonly property string systemHealth:     "heart-pulse"
    readonly property string settings:         "settings"

    // ---- Status ----
    readonly property string success:          "check"
    readonly property string warning:          "alert-triangle"
    readonly property string danger:           "x"
    readonly property string info:             "info"
    readonly property string offline:          "wifi-off"
    readonly property string online:           "wifi"
    readonly property string unknown:          "circle-dot"
    readonly property string inactive:         "circle-dot"
    readonly property string pending:          "clock"
    readonly property string alertCircle:      "alert-circle"
    readonly property string alertTriangle:    "alert-triangle"

    // ---- Actions ----
    readonly property string play:             "play"
    readonly property string pause:            "pause"
    readonly property string mute:             "volume-x"
    readonly property string unmute:           "volume-2"
    readonly property string check:            "check"
    readonly property string close:            "x"
    readonly property string deleteIcon:       "trash-2"
    readonly property string edit:             "pencil"
    readonly property string save:             "save"
    readonly property string refresh:          "rotate-cw"
    readonly property string search:           "search"
    readonly property string filter:           "filter"
    readonly property string add:              "plus"
    readonly property string removeIcon:       "minus"
    readonly property string download:         "download"
    readonly property string upload:           "upload"
    readonly property string exportIcon:       "export"
    readonly property string externalLink:     "external-link"
    readonly property string copy:             "copy"
    readonly property string maximize:         "maximize"
    readonly property string minimize:         "minimize"
    readonly property string power:            "power"
    readonly property string logOut:           "log-out"

    // ---- UI chrome ----
    readonly property string menu:             "menu"
    readonly property string chevronRight:     "chevron-right"
    readonly property string chevronLeft:      "chevron-left"
    readonly property string chevronDown:      "chevron-down"
    readonly property string chevronUp:        "chevron-up"
    readonly property string arrowLeft:        "arrow-left"
    readonly property string arrowRight:       "arrow-right"
    readonly property string moreHorizontal:   "more-horizontal"
    readonly property string moreVertical:     "more-vertical"
    readonly property string grid:             "grid"
    readonly property string list:             "list"
    readonly property string home:             "home"
    readonly property string sun:              "sun"
    readonly property string moon:             "moon"

    // ---- Security / identity ----
    readonly property string lock:             "lock"
    readonly property string unlock:           "unlock"
    readonly property string key:              "key"
    readonly property string eye:              "eye"
    readonly property string eyeOff:           "eye-off"
    readonly property string userPlus:         "user-plus"
    readonly property string userX:            "user-x"

    // ---- Categories / infra ----
    readonly property string ai:               "bot"
    readonly property string storage:          "hard-drive"
    readonly property string security:         "shield"
    readonly property string camera:           "camera"
    readonly property string video:            "video"
    readonly property string target:           "target"
    readonly property string mail:             "mail"
    readonly property string inbox:            "inbox"
    readonly property string lightning:        "zap"
    readonly property string person:           "user"
    readonly property string people:           "users"
    readonly property string cpu:              "cpu"
    readonly property string server:           "server"
    readonly property string database:         "database"
    readonly property string network:          "network"
    readonly property string monitor:          "monitor"
    readonly property string layers:           "layers"
    readonly property string building:         "building"
    readonly property string doorOpen:         "door-open"
    readonly property string mapPin:           "map-pin"
    readonly property string clock:            "clock"
    readonly property string history:          "history"
    readonly property string gauge:            "gauge"
    readonly property string barChart:         "bar-chart-2"
    readonly property string sliders:          "sliders"
    readonly property string terminal:         "terminal"
    readonly property string radio:            "radio"
    readonly property string crosshair:        "crosshair"
    readonly property string file:             "file"
    readonly property string fileText:         "file-text"
    readonly property string clipboard:        "clipboard"
    readonly property string bookmark:         "bookmark"
    readonly property string box:              "box"
    readonly property string wifi:             "wifi"

    // ---- Empty / placeholder ----
    readonly property string empty:            "circle-dot"
    readonly property string noData:           "circle-dot"
    readonly property string noCamera:         "camera"

    // ---- Glyph aliases (backward compat) ----
    readonly property string alertGlyph:         "bell"
    readonly property string aiTrainingGlyph:    "bot"
    readonly property string observabilityGlyph: "activity"
    readonly property string eventsGlyph:        "calendar"
    readonly property string successGlyph:       "check"
}
